config/routes.rb
TestApp::Application.routes.draw do
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, :only => [:create, :destroy]
    resources :relationships, :only => [:create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/about', :to => 'pages#about'
    match '/help', :to => 'pages#help'
    match '/contact', :to => 'pages#contact'

    root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %>
            prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
        <p>There were problems with the following fields:</p>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
    <table class="microposts" summary="User microposts">
        <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
    </table>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
    <td class="gravatar">
        <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    </td>
    <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
        <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
    </td>
    <% if current_user?(feed_item.user) %>
        <td>
            <%= link_to "delete", feed_item, :method => :delete,
                        :confirm => "You sure?",
                        :title => feed_item.content %>
        </td>
    <% end %>
</tr>

app/views/shared/_micropost.html.erb
<tr>
    <td class="micropost">
        <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
    </td>

    <% if current_user?(micropost.user) %>
        <td>
            <%= link_to "delete", micropost, :method => :delete,
                        :confirm => "You sure?",
                        :title => micropost.content %>
        </td>
    <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
        <%= f.text_area :content %>
    </div>
    <div class="actions">
        <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <table summary="User stats">
        <tr>
            <td>
                <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
                </a>
            </td>
            <td>
                <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
                </a>
            </td>
        </tr>
    </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
    <a href="<%= user_path(current_user) %>">
        <%= gravatar_for current_user, :size => 30 %>
        <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
    </a>
</div>