config/routes.rb
TestApp::Application.routes.draw do
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, :only => [:create, :destroy]
    resources :relationships, :only => [:create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/about', :to => 'pages#about'
    match '/help', :to => 'pages#help'
    match '/contact', :to => 'pages#contact'

    root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    <%= javascript_include_tag :defaults %>
</head>
<body>
<div class="container">
    <header>
        <% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
        <%= link_to logo, root_path %>
        <nav class="round">
            <ul>
                <li><%= link_to "Home", root_path %></li>
                <% if signed_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% end %>
                <li><%= link_to "Help", help_path %></li>
                <% if signed_in? %>
                    <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
                <% else %>
                    <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
            </ul>
        </nav>
    </header>
    <section class="round">
        <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
    </section>
    <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>